// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvbzzqjcfcwmnuqwjaya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2Ynp6cWpjZmN3bW51cXdqYXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDQ4ODYsImV4cCI6MjA2NjYyMDg4Nn0.onHznTmhctzHgFWuWgOYz_I3cfLpmsJmS0Kxm-tTqbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);